In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity


import warnings; warnings.simplefilter('ignore')

In [3]:
data = pd.read_csv("dogKor2.csv", encoding='utf8')


In [4]:
data


breed       temper popularity  \
0          말티즈     젠틀 장난 매력         33   
1          진도견     경고 지능 대담          -   
2        토이 푸들  \n민첩 지능 자신감          7   
3        포메라니안   호기심 대담 생동감         22   
4          치와와    챠밍 우아함 콧대         30   
5          스피츠    헌신 생동감 세심          -   
6           시츄    다정 장난 외향          20   
7         닥스훈트    친절 호기심 섹시         13   
8      골든 리트리버     친절 지능 헌신          3   
9      요크셔 테리어   다정 멋짐 말괄량이          9   
10    시베리안 허스키     충성 외향 장난         12   
11   라브라도 리트리버     친절 활동 외향          1   
12  웰시 코기 펨브로크     다정 똑똑 경고         18   
13     보스턴 테리어     친절 밝음 재미         21   
14     코카 스파니엘     젠틀 똑똑 행복         29   
15      프렌치 불독     적응 장난 똑똑          6   
16          비글    친절 호기심 명랑          5   
17    미니어쳐 핀셔     겁없는 재미 자랑         68   
18     비숑 프리제     장난 호기심 스릴         45   
19       보더 콜리     다정 영리 활기         38   

                                               height  \
0                                          7-9 inches   
1                                        18-22 inches   
2                              No more than 10 inches   
3                                          6-7 inches   
4                                          5-8 inches   
5                                        12-15 inches   
6                                       9-10.5 inches   
7       8-9 inches (standard), 5-6 inches (miniature)   
8      23-24 inches (male), 21.5-22.5 inches (female)   
9                                          7-8 inches   
10       21-23.5 inches (male), 20-22 inches (female)   
11  22.5-24.5 inches (male), 21.5-23.5 inches (fem...   
12                                       10-12 inches   
13                                       15-17 inches   
14  14.5-15.5 inches (male), 13.5-14.5 inches (fem...   
15                                       11-13 inches   
16                    13 inches & under, 13-15 inches   
17                                     10-12.5 inches   
18                                    9.5-11.5 inches   
19         19-22 inches (male), 18-21 inches (female)   

                                               weight life_min size  life_max  \
0                                      under 7 pounds       12    S        15   
1                                        30-50 pounds        -    M        14   
2                                          4-6 pounds       10    S        18   
3                                          3-7 pounds       12    S        16   
4                              not exceeding 6 pounds       14    S        16   
5                                        24-26 pounds       13    M        15   
6                                         9-16 pounds       10    S        18   
7   16-32 pounds (standard), 11 pounds & under (mi...       12    S        16   
8          65-75 pounds (male), 55-65 pounds (female)       10    L        12   
9                                            7 pounds       11    S        15   
10         45-60 pounds (male), 35-50 pounds (female)       12    M        14   
11         65-80 pounds (male), 55-70 pounds (female)       10    L        12   
12   up to 30 pounds (male), up to 28 pounds (female)       12    S        13   
13                                       12-25 pounds       11    S        13   
14         25-30 pounds (male), 20-25 pounds (female)       10    M        14   
15                                    under 28 pounds       10    S        12   
16  under 20 pounds (13 inches & under), 20-30 pou...       10    S        15   
17                                        8-10 pounds       12    S        16   
18                                       12-18 pounds       14    S        15   
19                                       30-55 pounds       12    M        15   

   GROOMING - Grooming Frequency (%) GROOMING - Shedding (%)  \
0                                80%                     20%   
1                                40%                     60%   
2                               10

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [6]:
count_vector = CountVectorizer(ngram_range=(1,3))


In [7]:
count_vector

CountVectorizer(ngram_range=(1, 3))

In [8]:
c_vector_keyword = count_vector.fit_transform(data['temper'])

In [9]:
c_vector_keyword.shape

(20, 93)

In [10]:
c_vector_keyword.toarray() 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

In [12]:
specal_c_sim = cosine_similarity(c_vector_keyword, c_vector_keyword).argsort()[:,::-1]

In [13]:
specal_c_sim.shape

(20, 20)

In [14]:
specal_c_sim

array([[ 0, 15, 14, 10, 18,  6,  7,  1,  2,  3,  4,  5, 19,  8, 11, 12,
        13, 16, 17,  9],
       [ 1,  8,  2,  3, 12, 19,  4,  5,  6,  7,  9, 18, 10, 11, 13, 14,
        15, 16, 17,  0],
       [ 2,  1,  8, 19, 18,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 3,  1, 16,  5,  7, 18, 19,  8,  2,  4,  6,  9, 10, 11, 12, 13,
        14, 15, 17,  0],
       [ 4, 19, 18,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 5,  3,  8, 19, 18,  1,  2,  4,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 6, 10, 19, 12, 18, 11,  9, 15,  0, 13, 14, 16,  8,  7, 17,  5,
         4,  3,  2,  1],
       [ 7, 16,  3, 13, 11, 18,  8, 19,  6,  1,  2,  4,  5,  9, 10, 12,
        14, 15, 17,  0],
       [ 8,  7,  1, 16,  2, 13, 11,  5, 19,  3,  4,  6,  9, 18, 10, 12,
        14, 15, 17,  0],
       [ 9, 12,  6, 19, 15, 14, 13, 16, 11, 10, 18,  8,  7, 17,  5,  4,
         3,  2,  1,  0],
       [10,  6,  0, 15, 11, 18

In [20]:
def get_recommend_dog_list(df, dog_breed, top=10):
    # 특정 영화와 비슷한 영화를 추천해야 하기 때문에 '특정 영화' 정보를 뽑아낸다.
    target_dog_index = df[df['breed'] == dog_breed].index.values
    
    #코사인 유사도 중 비슷한 코사인 유사도를 가진 정보를 뽑아낸다.
    sim_index = specal_c_sim[target_dog_index, :top].reshape(-1)
    #본인을 제외
    sim_index = sim_index[sim_index != target_dog_index]

    #data frame으로 만들고 vote_count으로 정렬한 뒤 return
    result = df.iloc[sim_index][:10]
    return result

In [21]:
get_recommend_dog_list(data, dog_breed="말티즈")

breed       temper popularity  \
15    프렌치 불독     적응 장난 똑똑          6   
14   코카 스파니엘     젠틀 똑똑 행복         29   
10  시베리안 허스키     충성 외향 장난         12   
18   비숑 프리제     장난 호기심 스릴         45   
6         시츄    다정 장난 외향          20   
7       닥스훈트    친절 호기심 섹시         13   
1        진도견     경고 지능 대담          -   
2      토이 푸들  \n민첩 지능 자신감          7   
3      포메라니안   호기심 대담 생동감         22   

                                               height  \
15                                       11-13 inches   
14  14.5-15.5 inches (male), 13.5-14.5 inches (fem...   
10       21-23.5 inches (male), 20-22 inches (female)   
18                                    9.5-11.5 inches   
6                                       9-10.5 inches   
7       8-9 inches (standard), 5-6 inches (miniature)   
1                                        18-22 inches   
2                              No more than 10 inches   
3                                          6-7 inches   

                                               weight life_min size  life_max  \
15                                    under 28 pounds       10    S        12   
14         25-30 pounds (male), 20-25 pounds (female)       10    M        14   
10         45-60 pounds (male), 35-50 pounds (female)       12    M        14   
18                                       12-18 pounds       14    S        15   
6                                         9-16 pounds       10    S        18   
7   16-32 pounds (standard), 11 pounds & under (mi...       12    S        16   
1                                        30-50 pounds        -    M        14   
2                                          4-6 pounds       10    S        18   
3                                          3-7 pounds       12    S        16   

   GROOMING - Grooming Frequency (%) GROOMING - Shedding (%)  \
15                               20%                     80%   
14                               80%                     40%   
10                               40%                     60%   
18                              100%                     20%   
6                                80%                     20%   
7                                40%                     40%   
1                                40%                     60%   
2                               100%                     20%   
3                                60%                     60%   

   EXERCISE - Energy Level (%) TRAINING - Trainability (%)  \
15                         40%                         60%   
14                         60%                        100%   
10                         80%                         40%   
18                         60%                         60%   
6                          60%                         60%   
7                          60%                         60%   
1                          80%                         40%   
2                          60%                        100%   
3                          60%                         60%   

   TRAINING - Temperament/Demeanor (%)  
15                                 60%  
14                                100%  
10                                 80%  
18                                100%  
6                                  80%  
7                                  60%  
1                                  40%  
2                                  80%  
3                                  60%

In [ ]:
//추천 여기까지

In [73]:
target_dog_index = data[data['breed']=='말티즈'].index.values

In [74]:
target_dog_index

array([0], dtype=int64)

In [71]:
specal_c_sim

array([[ 0, 15, 14, 10, 18,  6,  7,  1,  2,  3,  4,  5, 19,  8, 11, 12,
        13, 16, 17,  9],
       [ 1,  8,  2,  3, 12, 19,  4,  5,  6,  7,  9, 18, 10, 11, 13, 14,
        15, 16, 17,  0],
       [ 2,  1,  8, 19, 18,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 3,  1, 16,  5,  7, 18, 19,  8,  2,  4,  6,  9, 10, 11, 12, 13,
        14, 15, 17,  0],
       [ 4, 19, 18,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 5,  3,  8, 19, 18,  1,  2,  4,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 6, 10, 19, 12, 18, 11,  9, 15,  0, 13, 14, 16,  8,  7, 17,  5,
         4,  3,  2,  1],
       [ 7, 16,  3, 13, 11, 18,  8, 19,  6,  1,  2,  4,  5,  9, 10, 12,
        14, 15, 17,  0],
       [ 8,  7,  1, 16,  2, 13, 11,  5, 19,  3,  4,  6,  9, 18, 10, 12,
        14, 15, 17,  0],
       [ 9, 12,  6, 19, 15, 14, 13, 16, 11, 10, 18,  8,  7, 17,  5,  4,
         3,  2,  1,  0],
       [10,  6,  0, 15, 11, 18

In [77]:
sim_index = specal_c_sim[target_dog_index,:20].reshape(-1)

In [79]:
sim_index = sim_index[sim_index != target_dog_index]

In [81]:
 result = data.iloc[sim_index].sort_values('popularity', ascending=False)[:10]

In [82]:
result

breed       temper popularity  \
9    요크셔 테리어   다정 멋짐 말괄량이          9   
2      토이 푸들  \n민첩 지능 자신감          7   
17  미니어쳐 핀셔     겁없는 재미 자랑         68   
15    프렌치 불독     적응 장난 똑똑          6   
16        비글    친절 호기심 명랑          5   
18   비숑 프리제     장난 호기심 스릴         45   
19     보더 콜리     다정 영리 활기         38   
4        치와와    챠밍 우아함 콧대         30   
8    골든 리트리버     친절 지능 헌신          3   
14   코카 스파니엘     젠틀 똑똑 행복         29   

                                               height  \
9                                          7-8 inches   
2                              No more than 10 inches   
17                                     10-12.5 inches   
15                                       11-13 inches   
16                    13 inches & under, 13-15 inches   
18                                    9.5-11.5 inches   
19         19-22 inches (male), 18-21 inches (female)   
4                                          5-8 inches   
8      23-24 inches (male), 21.5-22.5 inches (female)   
14  14.5-15.5 inches (male), 13.5-14.5 inches (fem...   

                                               weight life_min size  life_max  \
9                                            7 pounds       11    S        15   
2                                          4-6 pounds       10    S        18   
17                                        8-10 pounds       12    S        16   
15                                    under 28 pounds       10    S        12   
16  under 20 pounds (13 inches & under), 20-30 pou...       10    S        15   
18                                       12-18 pounds       14    S        15   
19                                       30-55 pounds       12    M        15   
4                              not exceeding 6 pounds       14    S        16   
8          65-75 pounds (male), 55-65 pounds (female)       10    L        12   
14         25-30 pounds (male), 20-25 pounds (female)       10    M        14   

   GROOMING - Grooming Frequency (%) GROOMING - Shedding (%)  \
9                               100%                     20%   
2                               100%                     20%   
17                               20%                     NaN   
15                               20%                     80%   
16                               60%                     60%   
18                              100%                     20%   
19                               60%                     60%   
4                                20%                     40%   
8                                40%                     60%   
14                               80%                     40%   

   EXERCISE - Energy Level (%) TRAINING - Trainability (%)  \
9                          60%                         20%   
2                          60%                        100%   
17                         60%                         40%   
15                         40%                         60%   
16                         80%                         60%   
18                         60%                         60%   
19                        100%                        100%   
4                          60%                         40%   
8                         100%                        100%   
14                         60%                        100%   

   TRAINING - Temperament/Demeanor (%)  
9                                  80%  
2                                  80%  
17                                 60%  
15                                 60%  
16                                 80%  
18                                100%  
19                                 40%  
4                                  60%  
8                                  80%  
14                                100%

In [48]:
data.columns


Index(['breed', 'temper', 'popularity', 'height', 'weight', 'life_min', 'size',
       'life_max', 'GROOMING - Grooming Frequency (%)',
       'GROOMING - Shedding (%)', 'EXERCISE - Energy Level (%)',
       'TRAINING - Trainability (%)', 'TRAINING - Temperament/Demeanor (%)'],
      dtype='object')

In [67]:
get_recommend_movie_list(data, breed="말티즈")

TypeError: get_recommend_movie_list() got an unexpected keyword argument 'breed'