In [1]:
import pandas as pd


In [2]:
data = pd.read_csv("dogutf.csv", encoding='utf8')

In [16]:
#data = pd.read_csv('dog.csv', encoding='unicode_escape')

In [3]:
data


dog_id       age    weight  sex       kind  color  neuter  \
0     N448534202000837  2020(년생)     1(Kg)    F        믹스견    검은색       N   
1     N448534202000836  2020(년생)     1(Kg)    M        믹스견    검은색       N   
2     N448534202000835  2020(년생)     1(Kg)    M        믹스견    검은색       N   
3     N448534202000834  2020(년생)     1(Kg)    F        믹스견    검은색       N   
4     N448534202000833  2020(년생)     1(Kg)    F        믹스견    검은색       N   
...                ...       ...       ...  ...        ...    ...     ...   
5395  N441378202001515  2017(년생)   6.9(Kg)    M         푸들     갈색       Y   
5396  N430368202000305  2016(년생)     4(Kg)    F         시츄    백황색       U   
5397  N429363202000895  2019(년생)    13(Kg)    F        믹스견    검/갈       U   
5398  N428353202000715  2017(년생)  3.00(Kg)    M        스피츠  흰색/갈색       U   
5399  N426328202000330  2018(년생)     6(Kg)    F  웰시 코기 카디건    노란색       N   

                                               thumnail  \
0     http://www.animal.go.kr/files/shelter/2020/07/...   
1     http://www.animal.go.kr/files/shelter/2020/07/...   
2     http://www.animal.go.kr/files/shelter/2020/07/...   
3     http://www.animal.go.kr/files/shelter/2020/07/...   
4     http://www.animal.go.kr/files/shelter/2020/07/...   
...                                                 ...   
5395  http://www.animal.go.kr/files/shelter/2020/07/...   
5396  http://www.animal.go.kr/files/shelter/2020/07/...   
5397  http://www.animal.go.kr/files/shelter/2020/07/...   
5398  http://www.animal.go.kr/files/shelter/2020/07/...   
5399  http://www.animal.go.kr/files/shelter/2020/07/...   

                                                profile  \
0     http://www.animal.go.kr/files/shelter/2020/07/...   
1     http://www.animal.go.kr/files/shelter/2020/07/...   
2     http://www.animal.go.kr/files/shelter/2020/07/...   
3     http://www.animal.go.kr/files/shelter/2020/07/...   
4     http://www.animal.go.kr/files/shelter/2020/07/...   
...                                                 ...   
5395  http://www.animal.go.kr/files/shelter/2020/07/...   
5396  http://www.animal.go.kr/files/shelter/2020/07/...   
5397  http://www.animal.go.kr/files/shelter/2020/07/...   
5398  http://www.animal.go.kr/files/shelter/2020/07/...   
5399  http://www.animal.go.kr/files/shelter/2020/07/...   

                                      careAddr  careNm\t  \
0                  경상남도 사천시 곤명면 흥신로 514 (곤명면)   사천시위탁관리소   
1                  경상남도 사천시 곤명면 흥신로 514 (곤명면)   사천시위탁관리소   
2                  경상남도 사천시 곤명면 흥신로 514 (곤명면)   사천시위탁관리소   
3                  경상남도 사천시 곤명면 흥신로 514 (곤명면)   사천시위탁관리소   
4                  경상남도 사천시 곤명면 흥신로 514 (곤명면)   사천시위탁관리소   
...                                        ...       ...   
5395        경기도 성남시 분당구 불정로 266 (수내동/ 유신제일조합)   펫토피아동물병원   
5396     대전광역시 유성구 갑동로15번길 20-39 (갑동) 대전동물보호센터  대전동물보호센터   
5397  광주광역시 북구 본촌마을길 25 (본촌동/ 건국동사무소) 광주 동물보호소  광주 동물보호소   
5398     인천광역시 계양구 다남로165번길 56 (다남동/ 유기동물보호소)     인천수의사회   
5399                  부산광역시 강서구 제도로 726 (강동동)      하얀비둘기   

                           special              find_place    find_date   \
0      2개월령/ 어미개와 같이 구조된 6마리 중 1마리                은도원길12-19     20200911   
1      2개월령/ 어미개와 같이 구조된 6마리 중 1마리                은도원길12-19     20200911   
2      2개월령/ 어미개와 같이 구조된 6마리 중 1마리                은도원길12-19     20200911   
3     2개월령/ 어미개와 같이 구조된 6마리 중 1마리                 은도원길12-19     20200911   
4     2개월령/ 어미개와 같이 구조된 6마리 중 1마리                 은도원길12-19     20200911   
...                            ...                      ...          ...   
5395                  피부병/ 털엉킴 심함/                신촌동190-10     20200811   
5396                                대전광역시 대덕구 중리동 중리주민센터 주변     20200811   
5397           20-1173 머루/ 가죽목줄 착용                  광산구 진곡동     20200811   
5398                 앞다리 부상(왼쪽 깁스)          남동구 복개서로35번길 26     20200811   
5399                  영도구-173/ 가슴줄                 영도구청 당직실     20200811   

       end_date  
0      20200921  
1  

In [28]:
pd.set_option('display.max_row', 5000)
pd.set_option('display.max_columns', 100)

In [6]:
data[' kind'].value_counts


<bound method IndexOpsMixin.value_counts of 0             믹스견
1             믹스견
2             믹스견
3             믹스견
4             믹스견
          ...    
5395           푸들
5396           시츄
5397          믹스견
5398          스피츠
5399    웰시 코기 카디건
Name:  kind, Length: 5400, dtype: object>

In [9]:
data['kind']  = data[' kind'].str.strip()

In [29]:
kind = pd.DataFrame(data['kind'].value_counts())
kind

kind
믹스견             4267
말티즈              192
진도견              174
푸들               169
포메라니안             55
치와와               41
스피츠               41
시츄                38
닥스훈트              26
골든 리트리버           26
요크셔 테리어           25
시베리안 허스키          24
라브라도 리트리버         23
웰시 코기 펨브로크        21
보스턴 테리어           20
코카 스파니엘           17
발바리               13
믹스                13
프렌치 불독            12
비글                12
미니어쳐 핀셔           11
비숑 프리제            10
보더 콜리             10
웰시 코기 카디건          9
말라뮤트               9
슈나우져               8
미텔 스피츠             8
시바                 7
차우차우               7
퍼그                 7
포인터                7
불독                 6
셰퍼드                6
그레이 하운드            5
사모예드               5
그레이트 피레니즈          4
페키니즈               4
알라스칸 말라뮤트          3
혼합                 3
삽살개                3
도사                 3
발발이                3
마스티프               2
도베르만               2
풍산견                2
저먼 셰퍼드 독           2
달마시안               2
토이 푸들              2
올드 잉글리쉬 불독         2
아메리칸 코카 스파니엘       2
핏불테리어              2
셔틀랜드 쉽독            2
스피츠믹스              2
브리타니 스파니엘          2
잉글리쉬 코카 스파니엘       1
라이카                1
레이크랜드 테리어          1
잉글리쉬 포인터           1
바셋 하운드             1
샤페이                1
슈나믹스               1
그레이트 덴             1
진도                 1
빠삐용                1
블랙턴                1
셰퍼드믹스              1
리트리버               1
말티푸                1
아키다                1
실키테리어              1
잉글리쉬폭스하운드          1
동경견                1
기타                 1
잉글리쉬 스프링거 스파니엘     1
벨지안 셰퍼드 독          1
저먼 포인터             1
블랙탄                1
스탠다드 푸들            1
미니어쳐 푸들            1
폭스테리어              1
이탈리안 그레이 하운드       1
말티즈믹스              1
호피견                1

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'int'>

In [18]:
print(kind.to_numpy())

[4267  192  174  169   55   41   41   38   26   26   25   24   23   21
   20   17   13   13   12   12   11   10   10    9    9    8    8    7
    7    7    7    6    6    5    5    4    4    3    3    3    3    3
    2    2    2    2    2    2    2    2    2    2    2    2    1    1
    1    1    1    1    1    1    1    1    1    1    1    1    1    1
    1    1    1    1    1    1    1    1    1    1    1    1    1]


In [19]:
print(kind.unique())

[4267  192  174  169   55   41   38   26   25   24   23   21   20   17
   13   12   11   10    9    8    7    6    5    4    3    2    1]


In [4]:
data.columns

Index(['dog_id', ' age', ' weight', ' sex', ' kind', ' color', ' neuter',
       ' thumnail', ' profile', ' careAddr', ' careNm\t', ' special',
       ' find_place ', ' find_date ', ' end_date'],
      dtype='object')

In [5]:
data[' kind'].unique()


array(['믹스견', '말티즈', '그레이 하운드', '비글', '불독', '치와와', '푸들', '진도견', '코카 스파니엘',
       '보더 콜리', '시츄', '시베리안 허스키', '포메라니안', '믹스', '말티푸', '골든 리트리버', '말라뮤트',
       '셰퍼드', '웰시 코기 펨브로크', '닥스훈트', '사모예드', '미텔 스피츠', '프렌치 불독',
       '라브라도 리트리버', '시바', '포인터', '비숑 프리제', '스피츠', '웰시 코기 카디건', '보스턴 테리어',
       '혼합', '요크셔 테리어', '미니어쳐 핀셔', '브리타니 스파니엘', '발바리', '도베르만', '퍼그',
       '차우차우', '토이 푸들', '아키다', '달마시안', '슈나우져', '기타', '알라스칸 말라뮤트',
       '셔틀랜드 쉽독', '핏불테리어', '잉글리쉬폭스하운드', '페키니즈', '슈나믹스', '블랙탄', '저먼 셰퍼드 독',
       '블랙턴', '올드 잉글리쉬 불독', '아메리칸 코카 스파니엘', '바셋 하운드', '미니어쳐 푸들',
       '스탠다드 푸들', '빠삐용', '삽살개', '잉글리쉬 코카 스파니엘', '폭스테리어', '풍산견', '도사',
       '이탈리안 그레이 하운드', '스피츠믹스', '레이크랜드 테리어', '그레이트 피레니즈', '리트리버',
       '벨지안 셰퍼드 독', '잉글리쉬 포인터', '잉글리쉬 스프링거 스파니엘', '호피견', '셰퍼드믹스', '실키테리어',
       '마스티프', '그레이트 덴', '저먼 포인터', '발발이', '진도', '동경견', '말티즈믹스', '샤페이',
       '라이카'], dtype=object)

In [29]:
data[' kind'].count()

5400

In [6]:
data[' special'].head()

0     2개월령/ 어미개와 같이 구조된 6마리 중 1마리
1     2개월령/ 어미개와 같이 구조된 6마리 중 1마리
2     2개월령/ 어미개와 같이 구조된 6마리 중 1마리
3    2개월령/ 어미개와 같이 구조된 6마리 중 1마리 
4    2개월령/ 어미개와 같이 구조된 6마리 중 1마리 
Name:  special, dtype: object

In [7]:
data[' special'].unique()

array(['2개월령/ 어미개와 같이 구조된 6마리 중 1마리', '2개월령/ 어미개와 같이 구조된 6마리 중 1마리 ',
       '흰색바탕에 연한황색 무늬/ 구조된 6마리중  어미개', ..., '20-1173 머루/ 가죽목줄 착용',
       '앞다리 부상(왼쪽 깁스)', '영도구-173/ 가슴줄'], dtype=object)

In [8]:
count_vector = Count

NameError: name 'Count' is not defined

In [11]:
import sklearn

sklearn.__version__


'0.23.2'

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
count_vector = CountVectorizer(ngram_range=(1,3))

In [24]:
count_vector

CountVectorizer(ngram_range=(1, 3))

In [15]:
c_vector_keyword = count_vector.fit_transform(data[' special'])

In [16]:
c_vector_keyword.shape

(5400, 19559)

In [29]:
c_vector_keyword.toarray() 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
np.c_vector_keyword

NameError: name 'np' is not defined

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
specal_c_sim = cosine_similarity(c_vector_keyword, c_vector_keyword).argsort()[:,::-1]

In [21]:
specal_c_sim.shape

(5400, 5400)

In [22]:
def get_recommend_dog_list(df, dog_id, top=30):
 target_dog_index = df[df['dog_id']==dog_id].index.values
 sim_index = specal_c_sim['target_dog_index',:top].reshape(-1)
 
 result = df.iloc[sim_index].sort_values('score', ascending=False)[:10]
 return result
 

In [23]:
get_recommend_dog_list(data, dog_id="N441378202001515")

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [34]:
data = pd.read_csv("dogKor2.csv", encoding='utf8')


In [35]:
data


breed       temper popularity  \
0          말티즈     젠틀 장난 매력         33   
1          진도견     경고 지능 대담          -   
2        토이 푸들  \n민첩 지능 자신감          7   
3        포메라니안   호기심 대담 생동감         22   
4          치와와    챠밍 우아함 콧대         30   
5          스피츠    헌신 생동감 세심          -   
6           시츄    다정 장난 외향          20   
7         닥스훈트    친절 호기심 섹시         13   
8      골든 리트리버     친절 지능 헌신          3   
9      요크셔 테리어   다정 멋짐 말괄량이          9   
10    시베리안 허스키     충성 외향 장난         12   
11   라브라도 리트리버     친절 활동 외향          1   
12  웰시 코기 펨브로크     다정 똑똑 경고         18   
13     보스턴 테리어     친절 밝음 재미         21   
14     코카 스파니엘     젠틀 똑똑 행복         29   
15      프렌치 불독     적응 장난 똑똑          6   
16          비글    친절 호기심 명랑          5   
17    미니어쳐 핀셔     겁없는 재미 자랑         68   
18     비숑 프리제     장난 호기심 스릴         45   
19       보더 콜리     다정 영리 활기         38   

                                               height  \
0                                          7-9 inches   
1                                        18-22 inches   
2                              No more than 10 inches   
3                                          6-7 inches   
4                                          5-8 inches   
5                                        12-15 inches   
6                                       9-10.5 inches   
7       8-9 inches (standard), 5-6 inches (miniature)   
8      23-24 inches (male), 21.5-22.5 inches (female)   
9                                          7-8 inches   
10       21-23.5 inches (male), 20-22 inches (female)   
11  22.5-24.5 inches (male), 21.5-23.5 inches (fem...   
12                                       10-12 inches   
13                                       15-17 inches   
14  14.5-15.5 inches (male), 13.5-14.5 inches (fem...   
15                                       11-13 inches   
16                    13 inches & under, 13-15 inches   
17                                     10-12.5 inches   
18                                    9.5-11.5 inches   
19         19-22 inches (male), 18-21 inches (female)   

                                               weight life_min size  life_max  \
0                                      under 7 pounds       12    S        15   
1                                        30-50 pounds        -    M        14   
2                                          4-6 pounds       10    S        18   
3                                          3-7 pounds       12    S        16   
4                              not exceeding 6 pounds       14    S        16   
5                                        24-26 pounds       13    M        15   
6                                         9-16 pounds       10    S        18   
7   16-32 pounds (standard), 11 pounds & under (mi...       12    S        16   
8          65-75 pounds (male), 55-65 pounds (female)       10    L        12   
9                                            7 pounds       11    S        15   
10         45-60 pounds (male), 35-50 pounds (female)       12    M        14   
11         65-80 pounds (male), 55-70 pounds (female)       10    L        12   
12   up to 30 pounds (male), up to 28 pounds (female)       12    S        13   
13                                       12-25 pounds       11    S        13   
14         25-30 pounds (male), 20-25 pounds (female)       10    M        14   
15                                    under 28 pounds       10    S        12   
16  under 20 pounds (13 inches & under), 20-30 pou...       10    S        15   
17                                        8-10 pounds       12    S        16   
18                                       12-18 pounds       14    S        15   
19                                       30-55 pounds       12    M        15   

   GROOMING - Grooming Frequency (%) GROOMING - Shedding (%)  \
0                                80%                     20%   
1                                40%                     60%   
2                               10

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
count_vector = CountVectorizer(ngram_range=(1,3))


In [37]:
count_vector

CountVectorizer(ngram_range=(1, 3))

In [39]:
c_vector_keyword = count_vector.fit_transform(data['temper'])

In [40]:
c_vector_keyword.shape

(20, 93)

In [41]:
c_vector_keyword.toarray() 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [42]:
from sklearn.metrics.pairwise import cosine_similarity

In [43]:
specal_c_sim = cosine_similarity(c_vector_keyword, c_vector_keyword).argsort()[:,::-1]

In [44]:
specal_c_sim.shape

(20, 20)

In [46]:
specal_c_sim

array([[ 0, 15, 14, 10, 18,  6,  7,  1,  2,  3,  4,  5, 19,  8, 11, 12,
        13, 16, 17,  9],
       [ 1,  8,  2,  3, 12, 19,  4,  5,  6,  7,  9, 18, 10, 11, 13, 14,
        15, 16, 17,  0],
       [ 2,  1,  8, 19, 18,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 3,  1, 16,  5,  7, 18, 19,  8,  2,  4,  6,  9, 10, 11, 12, 13,
        14, 15, 17,  0],
       [ 4, 19, 18,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 5,  3,  8, 19, 18,  1,  2,  4,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 6, 10, 19, 12, 18, 11,  9, 15,  0, 13, 14, 16,  8,  7, 17,  5,
         4,  3,  2,  1],
       [ 7, 16,  3, 13, 11, 18,  8, 19,  6,  1,  2,  4,  5,  9, 10, 12,
        14, 15, 17,  0],
       [ 8,  7,  1, 16,  2, 13, 11,  5, 19,  3,  4,  6,  9, 18, 10, 12,
        14, 15, 17,  0],
       [ 9, 12,  6, 19, 15, 14, 13, 16, 11, 10, 18,  8,  7, 17,  5,  4,
         3,  2,  1,  0],
       [10,  6,  0, 15, 11, 18

In [62]:
def get_recommend_movie_list(df, dog_breed, top=10):
    # 특정 영화와 비슷한 영화를 추천해야 하기 때문에 '특정 영화' 정보를 뽑아낸다.
    target_movie_index = df[df['breed'] == dog_breed].index.values
    
    #코사인 유사도 중 비슷한 코사인 유사도를 가진 정보를 뽑아낸다.
    sim_index = specal_c_sim[target_movie_index, :top].reshape(-1)
    #본인을 제외
    sim_index = sim_index[sim_index != target_movie_index]

    #data frame으로 만들고 vote_count으로 정렬한 뒤 return
    result = df.iloc[sim_index][:10]
    return result

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
from surprise import Reader, Dataset, SVD, evaluate

import warnings; warnings.simplefilter('ignore')

ModuleNotFoundError: No module named 'nltk'

In [73]:
target_dog_index = data[data['breed']=='말티즈'].index.values

In [74]:
target_dog_index

array([0], dtype=int64)

In [71]:
specal_c_sim

array([[ 0, 15, 14, 10, 18,  6,  7,  1,  2,  3,  4,  5, 19,  8, 11, 12,
        13, 16, 17,  9],
       [ 1,  8,  2,  3, 12, 19,  4,  5,  6,  7,  9, 18, 10, 11, 13, 14,
        15, 16, 17,  0],
       [ 2,  1,  8, 19, 18,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 3,  1, 16,  5,  7, 18, 19,  8,  2,  4,  6,  9, 10, 11, 12, 13,
        14, 15, 17,  0],
       [ 4, 19, 18,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 5,  3,  8, 19, 18,  1,  2,  4,  6,  7,  9, 10, 11, 12, 13, 14,
        15, 16, 17,  0],
       [ 6, 10, 19, 12, 18, 11,  9, 15,  0, 13, 14, 16,  8,  7, 17,  5,
         4,  3,  2,  1],
       [ 7, 16,  3, 13, 11, 18,  8, 19,  6,  1,  2,  4,  5,  9, 10, 12,
        14, 15, 17,  0],
       [ 8,  7,  1, 16,  2, 13, 11,  5, 19,  3,  4,  6,  9, 18, 10, 12,
        14, 15, 17,  0],
       [ 9, 12,  6, 19, 15, 14, 13, 16, 11, 10, 18,  8,  7, 17,  5,  4,
         3,  2,  1,  0],
       [10,  6,  0, 15, 11, 18

In [77]:
sim_index = specal_c_sim[target_dog_index,:20].reshape(-1)

In [79]:
sim_index = sim_index[sim_index != target_dog_index]

In [81]:
 result = data.iloc[sim_index].sort_values('popularity', ascending=False)[:10]

In [82]:
result

breed       temper popularity  \
9    요크셔 테리어   다정 멋짐 말괄량이          9   
2      토이 푸들  \n민첩 지능 자신감          7   
17  미니어쳐 핀셔     겁없는 재미 자랑         68   
15    프렌치 불독     적응 장난 똑똑          6   
16        비글    친절 호기심 명랑          5   
18   비숑 프리제     장난 호기심 스릴         45   
19     보더 콜리     다정 영리 활기         38   
4        치와와    챠밍 우아함 콧대         30   
8    골든 리트리버     친절 지능 헌신          3   
14   코카 스파니엘     젠틀 똑똑 행복         29   

                                               height  \
9                                          7-8 inches   
2                              No more than 10 inches   
17                                     10-12.5 inches   
15                                       11-13 inches   
16                    13 inches & under, 13-15 inches   
18                                    9.5-11.5 inches   
19         19-22 inches (male), 18-21 inches (female)   
4                                          5-8 inches   
8      23-24 inches (male), 21.5-22.5 inches (female)   
14  14.5-15.5 inches (male), 13.5-14.5 inches (fem...   

                                               weight life_min size  life_max  \
9                                            7 pounds       11    S        15   
2                                          4-6 pounds       10    S        18   
17                                        8-10 pounds       12    S        16   
15                                    under 28 pounds       10    S        12   
16  under 20 pounds (13 inches & under), 20-30 pou...       10    S        15   
18                                       12-18 pounds       14    S        15   
19                                       30-55 pounds       12    M        15   
4                              not exceeding 6 pounds       14    S        16   
8          65-75 pounds (male), 55-65 pounds (female)       10    L        12   
14         25-30 pounds (male), 20-25 pounds (female)       10    M        14   

   GROOMING - Grooming Frequency (%) GROOMING - Shedding (%)  \
9                               100%                     20%   
2                               100%                     20%   
17                               20%                     NaN   
15                               20%                     80%   
16                               60%                     60%   
18                              100%                     20%   
19                               60%                     60%   
4                                20%                     40%   
8                                40%                     60%   
14                               80%                     40%   

   EXERCISE - Energy Level (%) TRAINING - Trainability (%)  \
9                          60%                         20%   
2                          60%                        100%   
17                         60%                         40%   
15                         40%                         60%   
16                         80%                         60%   
18                         60%                         60%   
19                        100%                        100%   
4                          60%                         40%   
8                         100%                        100%   
14                         60%                        100%   

   TRAINING - Temperament/Demeanor (%)  
9                                  80%  
2                                  80%  
17                                 60%  
15                                 60%  
16                                 80%  
18                                100%  
19                                 40%  
4                                  60%  
8                                  80%  
14                                100%

In [48]:
data.columns


Index(['breed', 'temper', 'popularity', 'height', 'weight', 'life_min', 'size',
       'life_max', 'GROOMING - Grooming Frequency (%)',
       'GROOMING - Shedding (%)', 'EXERCISE - Energy Level (%)',
       'TRAINING - Trainability (%)', 'TRAINING - Temperament/Demeanor (%)'],
      dtype='object')

In [67]:
get_recommend_movie_list(data, breed="말티즈")

TypeError: get_recommend_movie_list() got an unexpected keyword argument 'breed'